import './globals.css'
import {Creepster} from "next/font/google";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const patrick = Creepster({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({children}) {

  return (
      <html lang="en">
      <body className={"bg-neutral-900 p-4 max-w-[1200px] m-auto"}>{
        <>
          <div className={"sticky top-4 z-10 h-fit w-full p-2 bg-neutral-800 mb-4" +
              " rounded-xl border border-1 border-neutral-700 shadow-lg"}>
            <div className={patrick.className}>
              <div className={"bg-red-500/10 w-fit h-fit py-1 px-2 rounded-md"}>
                <h1 className={"font-bold text-2xl text-red-500 tracking-wider"}>Giggity</h1>
              </div>
            </div>
          </div>
          {children}

        </>
      }</body>
      </html>
  )
}
