export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SingleGigLayout({children}) {

  return (
      <div>
        <>
          {children}
        </>
      </div>
  )
}
